import type { CreateGamifyQuestDefinition } from './GamifyQuestCatalogService'

/** Published reward amounts and targets remain unchanged. Claims are saved
 * review choices, not proof of contact. Conversion quests are suspended until
 * a verified conversion producer exists. Reports never mint quest XP. */
export const GAMIFY_QUEST_CATALOG: CreateGamifyQuestDefinition[] = [
  {
    code: 'first_contact',
    version: 1,
    title: 'First lead saved',
    description: 'Review a signal and claim it for follow-up. Claiming does not mark it contacted.',
    type: 'ONBOARDING',
    eventType: 'opportunity.engaged',
    target: 1,
    rewardXp: 50,
  },
  {
    code: 'first_conversion',
    version: 1,
    title: 'First Blood',
    description: 'Turn a claimed signal into a converted lead.',
    type: 'ONBOARDING',
    eventType: 'lead.converted',
    enabled: false,
    target: 1,
    rewardXp: 200,
  },
  {
    code: 'daily_patrol',
    version: 1,
    title: 'Daily Patrol',
    description: 'Claim three signals today.',
    type: 'DAILY',
    eventType: 'opportunity.engaged',
    target: 3,
    rewardXp: 40,
  },
  {
    code: 'weekly_sweep',
    version: 1,
    title: 'Weekly Sweep',
    description: 'Claim fifteen signals this week.',
    type: 'WEEKLY',
    eventType: 'opportunity.engaged',
    target: 15,
    rewardXp: 150,
  },
  {
    code: 'weekly_closer',
    version: 1,
    title: 'Weekly Closer',
    description: 'Convert two leads this week.',
    type: 'WEEKLY',
    eventType: 'lead.converted',
    enabled: false,
    target: 2,
    rewardXp: 300,
  },
  {
    code: 'milestone_fifty_claims',
    version: 1,
    title: 'Field Veteran',
    description: 'Claim fifty signals in total.',
    type: 'MILESTONE',
    eventType: 'opportunity.engaged',
    target: 50,
    rewardXp: 500,
  },
  {
    code: 'milestone_ten_conversions',
    version: 1,
    title: 'Rainmaker',
    description: 'Convert ten leads in total.',
    type: 'MILESTONE',
    eventType: 'lead.converted',
    enabled: false,
    target: 10,
    rewardXp: 1_000,
  },
]
